name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Build Docker Image
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/electionCapping24:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/electionCapping24:latest

  # Deploy to Server
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | ssh-add -
          ssh -o StrictHostKeyChecking=no developer@10.11.29.103 << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/electionCapping24:latest
            docker stop electionCapping24 || true
            docker rm electionCapping24 || true
            docker run -d --name electionCapping24 -p 80:80 ${{ secrets.DOCKER_USERNAME }}/electionCapping24:latest
          EOF
