name: Deploy to Server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Server
      env:
        SSH_IP: 10.11.29.103
        SSH_USER: root
        SSH_PASSWORD: MaristDev2024!
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_IP << 'EOF'
          # Navigate to the app directory or clone it if not present
          cd /path/to/your-app || git clone https://github.com/your-username/electionCapping24.git /path/to/your-app && cd /path/to/your-app
          
          # Pull the latest changes
          git pull origin main
          
          # Install dependencies (assuming Node.js; adjust as needed)
          npm install
          
          # Restart the app (using pm2, nohup, or similar)
          pm2 restart app || pm2 start app.js --name app
        EOF
