name: Deploy to Server via SSH

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 10.11.29.103
        username: developer
        key: 717288384919whqjainwn18274
        script: |
          # Navigate to the app directory or clone it if not present
          cd /path/to/your-app || git clone https://github.com/your-username/electionCapping24.git /path/to/your-app && cd /path/to/your-app
          
          # Pull the latest changes
          git pull origin main
          
          # Install dependencies (assuming Node.js; adjust as needed)
          npm install
          
          # Restart the app (using pm2, nohup, or similar)
          pm2 restart app || pm2 start app.js --name app

